### ISSUE TITLE
noarch, long running branch for 0.17.x?

### ISSUE THREAD

**Issue by bollwyvl** [conda-forge/jedi-feedstock#40]
Hello! We're still stuck with `jedi=0.17` on https://github.com/conda-forge/ipython-feedstock/pull/123. Can we get a long-running `0.17.x` branch, i guess from #33 (b1a51e1)?

Further, is there a compelling reason it (and master) can't be `noarch: python`? Otherwise, will have to figure out how to get it added to the `pypy37` migration...

**Comment by asmeurer** [comment]
Is there documentation on how to create a long running branch?

**Comment by bollwyvl** [comment]
Ha, it's the [_very last_ thing](https://conda-forge.org/docs/maintainer/updating_pkgs.html?highlight=branch#maintaining-several-versions) on the docs, but it's there!

Anyhow, I think anybody with push rights could:
```
git checkout v0.17.x
git reset --hard b1a51e1
git push origin v0.17.x
```

That would trigger a build, but nothing would get published.

Then, in this case, there could be this pull request against `v0.17.x`:
- make it `noarch: python`, and then the branch will probably never be updated until some upstream makes an API-incompatible change and a top pin becomes necessary
  - the bot can be [summoned](https://conda-forge.org/docs/maintainer/infrastructure.html#conda-forge-admin-please-add-noarch-python) to make this PR 

...or this one against `master` (I think!):
- add to [conda-forge.yml](https://conda-forge.org/docs/maintainer/conda_forge_yml.html?highlight=bot#bot) 
  ```yaml
  bot:
    ...
    # any branches listed in this section will get bot migration PRs in addition
    # to the default branch
    abi_migration_branches:
      - v0.17.x
  ``` 

  - Wait for the bot to make a `pypy37` migration
  - keep getting bot PRs later on down the line

But yeah, maybe there should be a set of links to guide between those `n` places!

**Comment by mattip** [comment]
I am not sure I understand the problem here, but it would be nice to get this fixed for the pypy3.7 migration. Is there something I can do?

**Comment by h-vetinari** [comment]
> 
> 
> I am not sure I understand the problem here, but it would be nice to get this fixed for the pypy3.7 migration. Is there something I can do?

@conda-forge/jedi or @conda-forge/core would need to create a branch for 0.17.

PS. We don't specifically need to activate the bot for it as @bollwyvl [describes](https://github.com/conda-forge/jedi-feedstock/issues/40#issuecomment-756487058) (although that's certainly the more sustainable solution) - it could then also be done as a simple manual migration (copying `pypy37.yaml` to `.ci_support/migrations` and rerendering).

**Comment by pkgw** [comment]
I am literally just now downgrading my jedi from 0.18 to 0.17 to fix ipython, so I'm feeling the pain here. Do we expect to need a long-lived branch? I'm wondering if a new ipython release will make this all a moot point. (The only issue I'm aware with is the ipython compat ... are there others?)

**Comment by nehaljwani** [comment]
I just merged a change as per @h-vetinari's instructions.

**Comment by pkgw** [comment]
Does #34 mean that parso is going to need a branch too?

**Comment by nehaljwani** [comment]
> ...or this one against `master` (I think!):
> 
> * add to [conda-forge.yml](https://conda-forge.org/docs/maintainer/conda_forge_yml.html?highlight=bot#bot)
>   ```yaml
>   bot:
>     ...
>     # any branches listed in this section will get bot migration PRs in addition
>     # to the default branch
>     abi_migration_branches:
>       - v0.17.x
>   ```
>   
>   
>   
>   * Wait for the bot to make a `pypy37` migration
>   * keep getting bot PRs later on down the line
> 
> But yeah, maybe there should be a set of links to guide between those `n` places!

I've added this change to the master branch as well.

**Comment by nehaljwani** [comment]
> Does #34 mean that parso is going to need a branch too?

AFAIK parso is already noarch, so the long standing branch isn't required for migrations on that feedstock. However, if parso devs intend to continue cutting releases for versions < 0.8.0 and conda-forge intends to support that, then we'll probably need a long standing branch. I would've created one, but I am not a maintainer there.

**Comment by nehaljwani** [comment]
> Further, is there a compelling reason it (and master) can't be `noarch: python`?

Honestly, I don't remember. I guess someone needs to try it out!

**Comment by pkgw** [comment]
I think I should be able to add a branch to parso if needed — let me know.

**Comment by h-vetinari** [comment]
Cool, thanks for the quick action @nehaljwani!

**Comment by bollwyvl** [comment]
I see https://github.com/conda-forge/jedi-feedstock/tree/0.17.x exists and has pypy37 releases, hooray!
